### ISSUE TITLE
Error "unknown 30" occurs - see attachment

### ISSUE THREAD

**Issue by michael-spengler** [Bkindmonk/RepoCompanyCount#1]
![screen shot 2019-01-08 at 3 48 11 pm](https://user-images.githubusercontent.com/43786652/50837820-e0be5600-135c-11e9-8839-4fb93f1ef1c3.jpg)

**Comment by Bkindmonk** [comment]
I tested every component separately, but I didn't have much time to test everything together, because of the access limit of GitHub. I will test it later today again.

**Comment by michael-spengler** [comment]
ok
